extern word ikones;
extern word boldcz;
extern word sipka;
extern word font6x9;
extern void *bbutt;
extern word *vga_font;
extern word *icones;
extern word icone_color[];
extern word ramecek;
extern word *ramecky[];

//#define WINCOLOR 0x6318
#define WINCOLOR (31*1024+31*32+26)
#define LABELCOLOR (11*1024+11*32+06)
#define BUTTONCOLOR (28*1024+24*32+3)

#define PRG_HEADER "The Gates of Skeldal Setup v1."VERSION
extern FILE *ini;
